matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
language: c++

before_install: true

install: true

before_script:
    ./ci/builds/ci-travis.sh

script: true

after_script: true

addons: true

notifications:

cache: ccache
