language: c++
sudo: required
dist: trusty

matrix:
    include:
        - os: linux
        - os: osx
          osx_image: xcode6.4

before_install:
    - /bin/sh -x ./ci/before_install.sh

install:
    - /bin/sh -x ./ci/install.sh

before_script:
    - if [ "$TRAVIS_EVENT_TYPE" = "push" ] || [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then ccache -s; fi
    - /bin/sh -x ./ci/before_script.sh
    - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then export linenumber=`awk '/CFBundleShortVersionString/{ print NR; exit }' $TRAVIS_BUILD_DIR/examples/pxScene2d/src/macstuff/Info.plist`;export PX_VERSION=`sed -n "\`echo $((linenumber+1))\`p" $TRAVIS_BUILD_DIR/examples/pxScene2d/src/macstuff/Info.plist|awk -F '<string>' '{print $2}'|awk -F'</string>' '{print $1}'`; fi

script:
    - /bin/sh -x ./ci/script.sh
    - if [ "$TRAVIS_EVENT_TYPE" = "push" ] || [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then codecov --build "$TRAVIS_OS_NAME-$TRAVIS_COMMIT-$TRAVIS_BUILD_NUMBER" -X gcov -f $TRAVIS_BUILD_DIR/tracefile ; fi
    - if [ "$TRAVIS_EVENT_TYPE" = "push" ] || [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then genhtml -o $TRAVIS_BUILD_DIR/logs/codecoverage $TRAVIS_BUILD_DIR/tracefile; fi

after_script:
    - /bin/sh -x ./ci/after_script.sh

cache:
    ccache: true
    directories:
        - $HOME/.ccache
        - $HOME/Library/Caches/Homebrew
    timeout: 900
