language: c++
sudo: required
dist: trusty

env:
    global:
        TEST_VAR=1

matrix:
    include:
        - os: linux
        - os: osx
          osx_image: xcode6.4
        - os: osx
          osx_image: xcode8.3
        - os: osx
          osx_image: xcode9
        - os: osx
          osx_image: xcode9.1
        - os: osx
          osx_image: xcode9.2

before_install:
    - /bin/sh -x ./ci/before_install.sh

install:
    - /bin/sh -x ./ci/install.sh

before_script:
    - /bin/sh -x ./ci/before_script.sh

script:
    - /bin/sh -x ./ci/script.sh

after_script:
    - /bin/sh -x ./ci/after_script.sh

cache:
    ccache: true
    directories:
        - $HOME/.ccache
        - $HOME/Library/Caches/Homebrew
    timeout: 600
