matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
#  - os: osx
#    osx_image: xcode6.4
language: c++

before_install: true

install: true

before_script:
    ./ci/builds/dw.sh ./ci/builds/runall.sh
script: true

after_script: true

addons: true

notifications:

cache: ccache
